"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-18 13:34:58.295095
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_types_active'), ['active'], unique=False)

    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('CLIENT', 'COACH', 'ADMIN', name='role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_persons_role'), ['role'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('channel_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('TELEGRAM', 'BALE', 'WEB', name='platform'), nullable=False),
    sa.Column('platform_user_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_user_id', name='uq_platform_user')
    )
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_identities_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_identities_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_identities_platform_user_id'), ['platform_user_id'], unique=False)

    op.create_table('class_registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('class_type_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_type_id'], ['class_types.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_registration_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_registration_requests_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_registration_requests_status'), ['status'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('class_type_id', sa.Integer(), nullable=False),
    sa.Column('sessions_total', sa.Integer(), nullable=False),
    sa.Column('tuition', sa.BigInteger(), nullable=False),
    sa.Column('gym_fee', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', 'PAUSED', name='coursestatus'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['class_type_id'], ['class_types.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_class_type_id'), ['class_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_status'), ['status'], unique=False)

    op.create_table('plan_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.Enum('TRAINING', 'NUTRITION', 'CUSTOM', name='plantype'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_requests_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_requests_status'), ['status'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.Enum('TRAINING', 'NUTRITION', 'CUSTOM', name='plantype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('original_filename', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_person_id'), ['person_id'], unique=False)

    op.create_table('attendance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT_ALLOWED', 'ABSENT_UNAUTHORIZED', 'COACH_CANCELLED', 'HOLIDAY', name='attendancestatus'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_events_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_events_session_date'), ['session_date'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('TUITION', 'GYM_FEE', 'OTHER', name='paymentkind'), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_person_id'))
        batch_op.drop_index(batch_op.f('ix_payments_course_id'))

    op.drop_table('payments')
    with op.batch_alter_table('attendance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_events_session_date'))
        batch_op.drop_index(batch_op.f('ix_attendance_events_course_id'))

    op.drop_table('attendance_events')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_person_id'))
        batch_op.drop_index(batch_op.f('ix_plans_active'))

    op.drop_table('plans')
    with op.batch_alter_table('plan_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_requests_status'))
        batch_op.drop_index(batch_op.f('ix_plan_requests_person_id'))

    op.drop_table('plan_requests')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_status'))
        batch_op.drop_index(batch_op.f('ix_courses_client_id'))
        batch_op.drop_index(batch_op.f('ix_courses_class_type_id'))

    op.drop_table('courses')
    with op.batch_alter_table('class_registration_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_registration_requests_status'))
        batch_op.drop_index(batch_op.f('ix_class_registration_requests_person_id'))

    op.drop_table('class_registration_requests')
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_identities_platform_user_id'))
        batch_op.drop_index(batch_op.f('ix_channel_identities_platform'))
        batch_op.drop_index(batch_op.f('ix_channel_identities_person_id'))

    op.drop_table('channel_identities')
    op.drop_table('settings')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_role'))
        batch_op.drop_index(batch_op.f('ix_persons_phone'))

    op.drop_table('persons')
    with op.batch_alter_table('class_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_types_active'))

    op.drop_table('class_types')
    # ### end Alembic commands ###
