"""add reminder_logs

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-18 13:36:16.694715
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('LOW_SESSIONS', 'COURSE_INACTIVE', name='reminderkind'), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.create_index('ix_reminder_course_kind', ['course_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_logs_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_logs_course_id'))
        batch_op.drop_index('ix_reminder_course_kind')

    op.drop_table('reminder_logs')
    # ### end Alembic commands ###
